service:
  port:
    name: http
    l4_protocol: TCP
    port: 8080
    targetPort: 8080
  label: batch-service-1-pg4rb3b6op
  name: batch-service-1-pg4rb3b6op
  selector: batch-service-1-pg4rb3b6op
  type:
  - ClusterIP
  - NodePort
namespace: wwww-dev
batch:
  name: batch-service-1-pg4rb3b6op
  image:
    name: batch-service-1-pg4rb3b6op
    tag: "8142-4702-batch-service-1-pg4rb3b6op-1f9ca21"
    secret: regsecret
  container:
    name: batch-service-1-pg4rb3b6op
  repo:
    url: turaco-dev-registry.turacocloud.com/dev-turaco-workspace-268/turaco
  backing: 
  volume:
    name: pvc-batch-service-1-pg4rb3b6op
  resource:
    request:
      memory: 250Mi
      cpu: 0.25
    limits:
      memory: 0Mi
      cpu: 0
pvc:
  name: pvc-batch-service-1-pg4rb3b6op
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
