service:
  port:
    name: http
    l4_protocol: TCP
    port: 8080
    targetPort: 8080
  label: batch-service-2-xnpgjl6yno
  name: batch-service-2-xnpgjl6yno
  selector: batch-service-2-xnpgjl6yno
  type:
  - ClusterIP
  - NodePort
namespace: wwww-dev
batch:
  name: batch-service-2-xnpgjl6yno
  image:
    name: batch-service-2-xnpgjl6yno
    tag: "8142-4702-batch-service-2-xnpgjl6yno-7ae0141"
    secret: regsecret
  container:
    name: batch-service-2-xnpgjl6yno
  repo:
    url: turaco-dev-registry.turacocloud.com/dev-turaco-workspace-268/turaco
  backing: 
  volume:
    name: pvc-batch-service-2-xnpgjl6yno
  resource:
    request:
      memory: 250Mi
      cpu: 0.25
    limits:
      memory: 0Mi
      cpu: 0
pvc:
  name: pvc-batch-service-2-xnpgjl6yno
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
