apiVersion: v1
stringData:
  .dockerconfigjson: |-
    {
      "auths": {
        "{{ .Values.secret.registry.url }}": {
          "username": "{{ .Values.secret.registry.username }}",
          "password": "{{ .Values.secret.registry.password }}",
          "email": "{{ .Values.secret.registry.email }}",
          "auth": "{{ printf "%s:%s" .Values.secret.registry.username .Values.secret.registry.password  | b64enc }}"
        }
      }
    }
kind: Secret
metadata:
  name: {{ default "regsecret" .Values.secret.registry.name }}
  namespace: {{ default "default" .Values.namespace }}
type: kubernetes.io/dockerconfigjson